### ISSUE TITLE
Sets background to white even when switched off!

### ISSUE THREAD

**Issue by palfrey** [iamjpg/Rocket-Readability#1]
This makes https://blog.joinmastodon.org/2018/11/from-tumblr-to-mastodon/ unreadable with this plugin enabled, unless you then switch it off.

**Comment by PurpleCodingWizard** [comment]
I experience a similar issue when viewing search results on https://startpage.com
I'm not sure why would it need to inject a white overlay or background on a webpage.

**Comment by iamjpg** [comment]
This was a problem with CSS scoping. Fixed in 0.0.6.
